<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKkGQnAM\App_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKkGQnAM/App_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/ContainerKkGQnAM.legacy');

    return;
}

if (!\class_exists(App_KernelEnvDebugContainer::class, false)) {
    \class_alias(\ContainerKkGQnAM\App_KernelEnvDebugContainer::class, App_KernelEnvDebugContainer::class, false);
}

return new \ContainerKkGQnAM\App_KernelEnvDebugContainer([
    'container.build_hash' => 'KkGQnAM',
    'container.build_id' => 'c22107d1',
    'container.build_time' => 1611815656,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKkGQnAM');
