<?php

namespace ContainerTRxi6ly;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5b83dTeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5b83dTe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5b83dTe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'PostCategoryRepository' => ['privates', 'App\\Repository\\PostCategoryRepository', 'getPostCategoryRepositoryService', true],
        ], [
            'PostCategoryRepository' => 'App\\Repository\\PostCategoryRepository',
        ]);
    }
}
