<?php

namespace ContainerUaGpjiO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBeforeEntityUpdatedEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PU.f4Mn.EasyCorp\Bundle\EasyAdminBundle\Event\BeforeEntityUpdatedEvent' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Event\BeforeEntityUpdatedEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.PU.f4Mn": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Event\\BeforeEntityUpdatedEvent" but no such service exists.');
    }
}
