<?php

namespace ContainerFwyfxQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Workflow_ProductPublishing_Listener_AuditTrailService extends App_KernelProdContainer
{
    /*
     * Gets the private '.workflow.Product_publishing.listener.audit_trail' shared service.
     *
     * @return \Symfony\Component\Workflow\EventListener\AuditTrailListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Symfony\Bridge\Monolog\Logger('workflow');
        $a->pushHandler(($container->privates['monolog.handler.console'] ?? $container->getMonolog_Handler_ConsoleService()));
        $a->pushHandler(($container->privates['monolog.handler.main'] ?? $container->getMonolog_Handler_MainService()));

        return $container->privates['.workflow.Product_publishing.listener.audit_trail'] = new \Symfony\Component\Workflow\EventListener\AuditTrailListener($a);
    }
}
