<?php

namespace ContainerFwyfxQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W6kz_E3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.w6kz.e3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w6kz.e3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'event' => ['privates', '.errored..service_locator.w6kz.e3.EasyCorp\\Bundle\\EasyAdminBundle\\Event\\BeforeEntityPersistedEvent', NULL, 'Cannot autowire service ".service_locator.w6kz.e3": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Event\\BeforeEntityPersistedEvent" but no such service exists.'],
        ], [
            'event' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Event\\BeforeEntityPersistedEvent',
        ]);
    }
}
