<?php

namespace ContainerFwyfxQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBeforeEntityPersistedEventService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.w6kz.e3.EasyCorp\Bundle\EasyAdminBundle\Event\BeforeEntityPersistedEvent' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Event\BeforeEntityPersistedEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.w6kz.e3": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Event\\BeforeEntityPersistedEvent" but no such service exists.');
    }
}
