<?php

namespace ContainerFwyfxQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegenrateRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\RegenrateRepository' shared autowired service.
     *
     * @return \App\Repository\RegenrateRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RegenrateRepository'] = new \App\Repository\RegenrateRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
