<?php

namespace ContainerKkGQnAM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Workflow_ProductPublishing_Listener_AuditTrailService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.workflow.Product_publishing.listener.audit_trail' shared service.
     *
     * @return \Symfony\Component\Workflow\EventListener\AuditTrailListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'workflow'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'AuditTrailListener.php';

        $a = new \Symfony\Bridge\Monolog\Logger('workflow');
        $a->pushHandler(($container->privates['monolog.handler.null_internal'] ?? ($container->privates['monolog.handler.null_internal'] = new \Monolog\Handler\NullHandler())));

        return $container->privates['.workflow.Product_publishing.listener.audit_trail'] = new \Symfony\Component\Workflow\EventListener\AuditTrailListener($a);
    }
}
