<?php

namespace ContainerKkGQnAM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NtFb_VFService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.NtFb.vF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NtFb.vF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'event' => ['privates', '.errored..service_locator.NtFb.vF.EasyCorp\\Bundle\\EasyAdminBundle\\Event\\AfterEntityPersistedEvent', NULL, 'Cannot autowire service ".service_locator.NtFb.vF": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Event\\AfterEntityPersistedEvent" but no such service exists.'],
        ], [
            'event' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Event\\AfterEntityPersistedEvent',
        ]);
    }
}
