<?php

namespace ContainerKkGQnAM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryAddedSubscriberService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\CategoryAddedSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\CategoryAddedSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'CategoryAddedSubscriber.php';

        return $container->privates['App\\EventSubscriber\\CategoryAddedSubscriber'] = new \App\EventSubscriber\CategoryAddedSubscriber(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')));
    }
}
