<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF7tV8QJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF7tV8QJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF7tV8QJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF7tV8QJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF7tV8QJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'F7tV8QJ',
    'container.build_id' => '448434dd',
    'container.build_time' => 1611750781,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF7tV8QJ');
